import './Js/modal-team-info.js';
import './Js/pagination';
// import './Js/pagination';
import './Js/informing';
import './Js/apiService';
import './Js/gallery';
import './Js/spinner';
import './Js/auth';
import './Js/buttons';
import './Js/refs';
import './Js/modal-one-movie';
